[theme]
base = "light"

primaryColor = "#0a85a7"
backgroundColor = "#17eddc"
secondaryBackgroundColor = "#FDEBDD"
textColor = "#0c1216"

[theme.sidebar]
backgroundColor = "#6aa8dd"
secondaryBackgroundColor = "#488f94"
textColor = "#08062b"